### ISSUE TITLE
Unable to download Red by using Wally

### ISSUE THREAD

**Issue by KevinGamer3D2** [Uncontained0/Red#1]
![image](https://user-images.githubusercontent.com/63291726/220124945-e41476f1-2e6a-439d-8307-89d5ddfe74ac.png)

**Comment by KevinGamer3D2** [comment]
I also did this correctly 
![image](https://user-images.githubusercontent.com/63291726/220125184-1e3fd35f-035b-4f48-864d-f91e03990764.png)

**Comment by jackhexed** [comment]
Hey my apologies for not seeing this sooner, my notification settings were bugged. If you could please show your entire manifest and the entire output I can help you further.

**Comment by KevinGamer3D2** [comment]
![image](https://user-images.githubusercontent.com/63291726/222868632-56af02b5-2555-451e-8c73-501eece441ca.png)
Never mind I got it work I just looked at https://github.com/Uncontained0/Red/blob/main/wally.toml and I changed the name "Red" to all lowercase "red"

Edit: Wally installation in the document is outdated
