### ISSUE TITLE
Namespace On method callback parameter type causes type checking errors in Roblox LSP

### ISSUE THREAD

**Issue by notshirovian** [Uncontained0/Red#2]
The [Roblox LSP](https://github.com/NightrainsRbx/RobloxLsp) type checker raises a warning for this code which is copied from the [documentation](https://redblox.dev/1.1/api/Server.html#on):
```lua
local Net = Red.Server("Foo")

Net:On("EventName", function(Player, Message)
	print(Player.Name .. " said: " .. Message)
end)
```

The warning:
> Type `(Player: any, Message: any) -> nil` could not be converted into `((Player, ...any) -> ...any)?`.

This warning doesn't appear in Roblox Studio's script editor even with strict mode.

**Comment by jackhexed** [comment]
Normally I would not be opposed to fixing this, but it creates type errors for Luau LSP and Roblox Studio users. Additionally, Red does not officially support Roblox LSP due to it's many issues with type checking compared to the Luau type engine. I'll make this more clear on the documentation.
